language: python
os: linux
dist: focal
jobs:
  include:
    - python: 3.6
      env: TOXV=py36
    - python: 3.7
      env: TOXV=py37
    - python: 3.8
      env: TOXV=py38
    - python: 3.9
      env: TOXV=py39
before_install:
  - pip install tox-travis poetry codecov
script:
  - tox -e clean,$TOXV,cov
after_success:
  - codecov
